nvhpc, cuda: switch back to cuda@12 and gcc@12 for nvidia

diff --git a/bluebrain/deployment/bin/configure-compilers b/bluebrain/deployment/bin/configure-compilers
--- a/bluebrain/deployment/bin/configure-compilers
+++ b/bluebrain/deployment/bin/configure-compilers
@@ -20,18 +20,18 @@ fi
 # Find the location of *any* GCC, disregarding the environment that's
 # active (-E).  Prefer the hash passed through by earlier stages, if
 # not available fall back to the crude version.
-LEGACY_GCC_DIR=$(spack -E location --install-dir ${LEGACY_GCC_HASH:-gcc@${LEGACY_GCC_VERSION}})
+#LEGACY_GCC_DIR=$(spack -E location --install-dir ${LEGACY_GCC_HASH:-gcc@${LEGACY_GCC_VERSION}})
 DEFAULT_GCC_DIR=$(spack -E location --install-dir ${DEFAULT_GCC_HASH:-gcc@${DEFAULT_GCC_VERSION}})
 # Use the Spack configuration to grab the matching module for GCC;
 # requires GCC to be compiler found beforehand.
-GCC_MODULES="$(spack -E config get compilers|sed -n "
-    /^\s*spec: gcc@${LEGACY_GCC_VERSION}/,/^\s*modules:/ {
-        /^\s*modules:/ {
-            s/^\s*modules: \[\(.*\)\]\$/\1/;
-            p;
-        }
-    }")"
-log "...using gcc ${LEGACY_GCC_VERSION} from ${LEGACY_GCC_DIR} for Intel (legacy) and NVHPC with module(s) ${GCC_MODULES}"
+#GCC_MODULES="$(spack -E config get compilers|sed -n "
+#    /^\s*spec: gcc@${LEGACY_GCC_VERSION}/,/^\s*modules:/ {
+#        /^\s*modules:/ {
+#            s/^\s*modules: \[\(.*\)\]\$/\1/;
+#            p;
+#        }
+#    }")"
+#log "...using gcc ${LEGACY_GCC_VERSION} from ${LEGACY_GCC_DIR} for Intel (legacy) and NVHPC with module(s) ${GCC_MODULES}"
 log "...using gcc ${DEFAULT_GCC_VERSION} from ${DEFAULT_GCC_DIR} for modern Intel"
 
 while read -r line; do
@@ -77,9 +77,9 @@ while read -r line; do
     fi
 
     GCC_DIR=${DEFAULT_GCC_DIR}
-    if [[ ${spec} = "intel@"* ]]; then
-        GCC_DIR=${LEGACY_GCC_DIR}
-    fi
+    #if [[ ${spec} = "intel@"* ]]; then
+    #    GCC_DIR=${LEGACY_GCC_DIR}
+    #fi
 
     if [[ ${spec} = *"intel"* ]]; then
         # update intel modules to use newer gcc in .cfg files
@@ -118,14 +118,14 @@ while read -r line; do
     cmd=${cmd/unload/show/}
     full_module_path="$(${cmd}|&sed -ne '2{s/:$// p}')"
     # Then append a bunch of other required modules
-    if [[ $line = *"nvhpc"* ]]; then
-        if [[ -n $GCC_MODULES ]]; then
-            full_module_path="${GCC_MODULES},${full_module_path}"
-        else
-            log "unable to add GCC module(s) to NVHPC definition"
-            exit 1
-        fi
-    fi
+    #if [[ $line = *"nvhpc"* ]]; then
+    #    if [[ -n $GCC_MODULES ]]; then
+    #        full_module_path="${GCC_MODULES},${full_module_path}"
+    #    else
+    #        log "unable to add GCC module(s) to NVHPC definition"
+    #        exit 1
+    #    fi
+    #fi
     spec=${spec%%[+ ]*}             # truncate variants
     spec=${spec/llvm/clang}         # LLVM identifies as clang
     spec=${spec/20.0.4/19.1.3.304}  # Intel identifies as an older version
