intel: include GCC modules

diff --git a/bluebrain/deployment/bin/configure-compilers b/bluebrain/deployment/bin/configure-compilers
--- a/bluebrain/deployment/bin/configure-compilers
+++ b/bluebrain/deployment/bin/configure-compilers
@@ -145,6 +145,19 @@ while read -r line; do
             log "unable to add binutils module to NVHPC definition"
             exit 1
         fi
+    elif [[ $line = "intel-oneapi-compilers@"* ]]; then
+        if [[ -n $GCC_MODULES ]]; then
+            full_module_path="${GCC_MODULES},${full_module_path}"
+        else
+            log "unable to add GCC module(s) to Intel One definition"
+            exit 1
+        fi
+        if [[ -n $BINUTILS_MODULE ]]; then
+            full_module_path="${BINUTILS_MODULE},${full_module_path}"
+        else
+            log "unable to add binutils module to Intel One definition"
+            exit 1
+        fi
     fi
     spec=${spec%%[+ ]*}             # truncate variants
     spec=${spec/llvm/clang}         # LLVM identifies as clang
